declare const styles: {
    testpart: string;
    container: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    wrap: string;
    description: string;
    'border-bottom': string;
    scroll: string;
    'scroll-horizontal': string;
    'stats-container': string;
    'expired-container': string;
    'expired-expired': string;
    'expired-toexpire': string;
    'expired-number': string;
    'expired-text': string;
    'expired-title': string;
    'table-rows-container': string;
    'table-row': string;
    'table-titles': string;
    text: string;
    'text-alt': string;
    button: string;
    label: string;
};
export default styles;
//# sourceMappingURL=SgStatsWebPart.module.scss.d.ts.map